# https://cloud.google.com/appengine/docs/flexible/java/configuring-your-app-with-app-yaml

runtime: java
env: flex

handlers:
- url: /.*
  script: this field is required, but ignored
  secure: always  # Require HTTPS

runtime_config:  # Optional
  jdk: openjdk8
  server: jetty9

automatic_scaling:
  min_num_instances: 1

health_check:
  enable_health_check: True
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2

env_variables:
