server:
  applicationConnectors:
  - type: http
    port: 9000
  adminConnectors:
  - type: http
    port: 9001
logging:
  level: INFO
  loggers:
      "io.dropwizard": INFO
  appenders:
  - type: console
    threshold: ALL
    timeZone: UTC+8
    target: stdout